

export const LOAD_GROUPS = 'dq/Group/LOAD_GROUPS'
export const LOAD_GROUPS_SUCCESS = 'dq/Group/LOAD_GROUPS_SUCCESS'
export const LOAD_GROUP_FAILURE = 'dq/Group/LOAD_GROUP_FAILURE'
export const ADD_GROUP = 'dq/Group/ADD_GROUP'
export const ADD_GROUP_SUCCESS = 'dq/Group/ADD_GROUP_SUCCESS'
export const ADD_GROUP_FAILURE = 'dq/Group/ADD_GROUP_FAILURE'
export const DELETE_GROUP = 'dq/Group/DELETE_GROUP'
export const DELETE_GROUP_SUCCESS = 'dq/Group/DELETE_GROUP_SUCCESS'
export const DELETE_GROUP_FAILURE = 'dq/Group/DELETE_GROUP_FAILURE'
// export const LOAD_GROUP_DETAIL = 'dq/Group/LOAD_GROUP_DETAIL'
// export const LOAD_GROUP_DETAIL_SUCCESS = 'dq/Group/LOAD_GROUP_DETAIL_SUCCESS'
export const EDIT_GROUP = 'dq/Group/EDIT_GROUP'
export const EDIT_GROUP_SUCCESS = 'dq/Group/EDIT_GROUP_SUCCESS'
export const EDIT_GROUP_FAILURE = 'dq/Group/EDIT_GROUP_FAILURE'
