import { createTypes } from 'utils/redux'

enum Types {
  LOAD_SOURCES = 'dq/Source/LOAD_SOURCES',
  LOAD_SOURCES_SUCCESS = 'dq/Source/LOAD_SOURCES_SUCCESS',
  LOAD_SOURCES_FAILURE = 'dq/Source/LOAD_SOURCES_FAILURE',

  LOAD_SOURCE_DETAIL = 'dq/Source/LOAD_SOURCE_DETAIL',
  LOAD_SOURCE_DETAIL_SUCCESS = 'dq/Source/LOAD_SOURCE_DETAIL_SUCCESS',
  LOAD_SOURCE_DETAIL_FAIL = 'dq/Source/LOAD_SOURCE_DETAIL_FAIL',

  ADD_SOURCE = 'dq/Source/ADD_SOURCE',
  ADD_SOURCE_SUCCESS = 'dq/Source/ADD_SOURCE_SUCCESS',
  ADD_SOURCE_FAILURE = 'dq/Source/ADD_SOURCE_FAILURE',

  DELETE_SOURCE = 'dq/Source/DELETE_SOURCE',
  DELETE_SOURCE_SUCCESS = 'dq/Source/DELETE_SOURCE_SUCCESS',
  DELETE_SOURCE_FAILURE = 'dq/Source/DELETE_SOURCE_FAILURE',

  EDIT_SOURCE = 'dq/Source/EDIT_SOURCE',
  EDIT_SOURCE_SUCCESS = 'dq/Source/EDIT_SOURCE_SUCCESS',
  EDIT_SOURCE_FAILURE = 'dq/Source/EDIT_SOURCE_FAILURE',

  TEST_SOURCE_CONNECTION = 'dq/Source/TEST_SOURCE_CONNECTION',
  TEST_SOURCE_CONNECTION_SUCCESS = 'dq/Source/TEST_SOURCE_CONNECTION_SUCCESS',
  TEST_SOURCE_CONNECTION_FAILURE = 'dq/Source/TEST_SOURCE_CONNECTION_FAILURE',

  RESET_SOURCE_CONNECTION = 'dq/Source/RESET_SOURCE_CONNECTION',
  RESET_SOURCE_CONNECTION_SUCCESS = 'dq/Source/RESET_SOURCE_CONNECTION_SUCCESS',
  RESET_SOURCE_CONNECTION_FAILURE = 'dq/Source/RESET_SOURCE_CONNECTION_FAILURE',

  GET_CSV_META_ID = 'dq/Source/GET_CSV_META_ID',
  GET_CSV_META_ID_SUCCESS = 'dq/Source/GET_CSV_META_ID_SUCCESS',
  GET_CSV_META_ID_FAILURE = 'dq/Source/GET_CSV_META_ID_FAILURE',

  LOAD_SOURCE_DATABASES = 'dq/Source/LOAD_SOURCE_DATABASES',
  LOAD_SOURCE_DATABASES_SUCCESS = 'dq/Source/LOAD_SOURCE_DATABASES_SUCCESS',
  LOAD_SOURCE_DATABASES_FAILURE = 'dq/Source/LOAD_SOURCE_DATABASES_FAILURE',

  LOAD_SOURCE_DATABASE_TABLES = 'dq/Source/LOAD_SOURCE_DATABASE_TABLES',
  LOAD_SOURCE_DATABASE_TABLES_SUCCESS = 'dq/Source/LOAD_SOURCE_DATABASE_TABLES_SUCCESS',
  LOAD_SOURCE_DATABASE_TABLES_FAILURE = 'dq/Source/LOAD_SOURCE_DATABASE_TABLES_FAILURE',

  LOAD_SOURCE_TABLE_COLUMNS = 'dq/Source/LOAD_SOURCE_TABLE_COLUMNS',
  LOAD_SOURCE_TABLE_COLUMNS_SUCCESS = 'dq/Source/LOAD_SOURCE_TABLE_COLUMNS_SUCCESS',
  LOAD_SOURCE_TABLE_COLUMNS_FAILURE = 'dq/Source/LOAD_SOURCE_TABLE_COLUMNS_FAILURE',

  LOAD_DATASOURCES_INFO = 'dq/Source/LOAD_DATASOURCES_INFO',
  LOAD_DATASOURCES_INFO_SUCCESS = 'dq/Source/LOAD_DATASOURCES_INFO_SUCCESS',
  LOAD_DATASOURCES_INFO_FAILURE = 'dq/Source/LOAD_DATASOURCES_INFO_FAILURE'
}

export const ActionTypes = createTypes(Types)
