
import { createTypes } from 'utils/redux'

enum Types {
  LOAD_DISPLAYS = 'dq/Display/LOAD_DISPLAYS',
  LOAD_DISPLAYS_SUCCESS = 'dq/Display/LOAD_DISPLAYS_SUCCESS',
  LOAD_DISPLAYS_FAILURE = 'dq/Display/LOAD_DISPLAYS_FAILURE',

  ADD_DISPLAY = 'dq/Display/ADD_DISPLAY',
  ADD_DISPLAY_SUCCESS = 'dq/Display/ADD_DISPLAY_SUCCESS',
  ADD_DISPLAY_FAILURE = 'dq/Display/ADD_DISPLAY_FAILURE',

  EDIT_DISPLAY = 'dq/Display/EDIT_DISPLAY',
  EDIT_DISPLAY_SUCCESS = 'dq/Display/EDIT_DISPLAY_SUCCESS',
  EDIT_DISPLAY_FAILURE = 'dq/Display/EDIT_DISPLAY_FAILURE',

  EDIT_CURRENT_DISPLAY = 'dq/Display/EDIT_CURRENT_DISPLAY',
  EDIT_CURRENT_DISPLAY_SUCCESS = 'dq/Display/EDIT_CURRENT_DISPLAY_SUCCESS',
  EDIT_CURRENT_DISPLAY_FAILURE = 'dq/Display/EDIT_CURRENT_DISPLAY_FAILURE',

  EDIT_CURRENT_SLIDE = 'dq/Display/EDIT_CURRENT_SLIDE',
  EDIT_CURRENT_SLIDE_SUCCESS = 'dq/Display/EDIT_CURRENT_SLIDE_SUCCESS',
  EDIT_CURRENT_SLIDE_FAILURE = 'dq/Display/EDIT_CURRENT_SLIDE_FAILURE',

  UPLOAD_CURRENT_SLIDE_COVER = 'dq/Display/UPLOAD_CURRENT_SLIDE_COVER',
  UPLOAD_CURRENT_SLIDE_COVER_SUCCESS = 'dq/Display/UPLOAD_CURRENT_SLIDE_COVER_SUCCESS',
  UPLOAD_CURRENT_SLIDE_COVER_FAILURE = 'dq/Display/UPLOAD_CURRENT_SLIDE_COVER_FAILURE',

  DELETE_DISPLAY = 'dq/Display/DELETE_DISPLAY',
  DELETE_DISPLAY_SUCCESS = 'dq/Display/DELETE_DISPLAY_SUCCESS',
  DELETE_DISPLAY_FAILURE = 'dq/Display/DELETE_DISPLAY_FAILURE',

  LOAD_DISPLAY_DETAIL = 'dq/Display/LOAD_DISPLAY_DETAIL',
  LOAD_DISPLAY_DETAIL_SUCCESS = 'dq/Display/LOAD_DISPLAY_DETAIL_SUCCESS',
  LOAD_DISPLAY_DETAIL_FAILURE = 'dq/Display/LOAD_DISPLAY_DETAIL_FAILURE',

  ADD_DISPLAY_LAYERS = 'dq/Display/ADD_DISPLAY_LAYERS',
  ADD_DISPLAY_LAYERS_SUCCESS = 'dq/Display/ADD_DISPLAY_LAYERS_SUCCESS',
  ADD_DISPLAY_LAYERS_FAILURE = 'dq/Display/ADD_DISPLAY_LAYERS_FAILURE',

  EDIT_DISPLAY_LAYERS = 'dq/Display/EDIT_DISPLAY_LAYERS',
  EDIT_DISPLAY_LAYERS_SUCCESS = 'dq/Display/EDIT_DISPLAY_LAYERS_SUCCESS',
  EDIT_DISPLAY_LAYERS_FAILURE = 'dq/Display/EDIT_DISPLAY_LAYERS_FAILURE',

  DELETE_DISPLAY_LAYERS = 'dq/Display/DELETE_DISPLAY_LAYERS',
  DELETE_DISPLAY_LAYERS_SUCCESS = 'dq/Display/DELETE_DISPLAY_LAYERS_SUCCESS',
  DELETE_DISPLAY_LAYERS_FAILURE = 'dq/Display/DELETE_DISPLAY_LAYERS_FAILURE',

  DRAG_SELECT_LAYER = 'dq/Display/DRAG_SELECT_LAYER',
  RESIZE_LAYERS = 'dq/Display/RESIZE_LAYERS',
  SELECT_LAYER = 'dq/Display/SELECT_LAYER',
  CLEAR_LAYERS_SELECTION = 'dq/Display/CLEAR_LAYERS_SELECTION',

  TOGGLE_LAYERS_RESIZING_STATUS= 'dq/Display/TOGGLE_LAYERS_RESIZING_STATUS',
  TOGGLE_LAYERS_DRAGGING_STATUS= 'dq/Display/TOGGLE_LAYERS_DRAGGING_STATUS',

  SHOW_EDITOR_BASELINES = 'dq/Display/SHOW_EDITOR_BASELINES',
  CLEAR_EDITOR_BASELINES = 'dq/Display/CLEAR_EDITOR_BASELINES',

  COPY_SLIDE_LAYERS = 'dq/Display/COPY_SLIDE_LAYERS',
  PASTE_SLIDE_LAYERS = 'dq/Display/PASTE_SLIDE_LAYERS',
  PASTE_SLIDE_LAYERS_SUCCESS = 'dq/Display/PASTE_SLIDE_LAYERS_SUCCESS',
  PASTE_SLIDE_LAYERS_FAILURE = 'dq/Display/PASTE_SLIDE_LAYERS_FAILURE',

  UNDO_OPERATION = 'dq/Display/UNDO_OPERATION',
  UNDO_OPERATION_SUCCESS = 'dq/Display/UNDO_OPERATION_SUCCESS',
  UNDO_OPERATION_FAILURE = 'dq/Display/UNDO_OPERATION_FAILURE',
  REDO_OPERATION = 'dq/Display/REDO_OPERATION',
  REDO_OPERATION_SUCCESS = 'dq/Display/REDO_OPERATION_SUCCESS',
  REDO_OPERATION_FAILURE = 'dq/Display/REDO_OPERATION_FAILURE',

  LOAD_DISPLAY_SHARE_LINK = 'dq/Display/LOAD_DISPLAY_SHARE_LINK',
  LOAD_DISPLAY_SHARE_LINK_SUCCESS = 'dq/Display/LOAD_DISPLAY_SHARE_LINK_SUCCESS',
  LOAD_DISPLAY_SECRET_LINK_SUCCESS = 'dq/Display/LOAD_DISPLAY_SECRET_LINK_SUCCESS',
  LOAD_DISPLAY_SHARE_LINK_FAILURE = 'dq/Display/LOAD_DISPLAY_SHARE_LINK_FAILURE',

  RESET_DISPLAY_STATE = 'dq/Display/RESET_DISPLAY_STATE',

  MONITORED_SYNC_DATA_ACTION = 'dq/Display/MONITORED_SYNC_DATA_ACTION',
  MONITORED_SEARCH_DATA_ACTION = 'dq/Display/MONITORED_SEARCH_DATA_ACTION',
  MONITORED_LINKAGE_DATA_ACTION = 'dq/Display/MONITORED_LINKAGE_DATA_ACTION',

  LOAD_CURRENT_PROJECT = 'dq/Display/LOAD_CURRENT_PROJECT',
  LOAD_CURRENT_PROJECT_SUCCESS = 'dq/Display/LOAD_CURRENT_PROJECT_SUCCESS'
}

export const ActionTypes = createTypes(Types)
